AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "**/*.slim"
    - "vendor/**/*"
    - "db/schema.rb"

Lint/EndAlignment:
  AlignWith: keyword

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/AlignArray:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AsciiComments:
  Enabled: false

Style/CaseIndentation:
  IndentWhenRelativeTo: end

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/Lambda:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/FrozenStringLiteralComment:
  Enabled: false
